service: serverless-client

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${self:custom.currentStage}

custom:
  currentStage: ${file(../serverless/serverless.yml):custom.currentStage}
  sitename: demo-bp-${self:service}-${self:custom.currentStage}
  s3Sync:
    - bucketName: ${self:custom.sitename}
      localDir: build

plugins:
  - serverless-s3-sync

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.sitename}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]
  Outputs:
    AdminBucket:
      Value: !Ref StaticSite